const colors = {
  light: {
    text: "#0f172a",
    tint: "#1e40af",
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#1e40af",
    primaryForeground: "#ffffff",
    secondary: "#eff6ff",
    secondaryForeground: "#1e3a8a",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#dbeafe",
    accentForeground: "#1e40af",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    income: "#22c55e",
    expense: "#ef4444",
    border: "#e2e8f0",
    input: "#e2e8f0",
  },

  dark: {
    text: "#f1f5f9",
    tint: "#3b82f6",
    background: "#0f172a",
    foreground: "#f1f5f9",
    card: "#1e293b",
    cardForeground: "#f1f5f9",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#1e3a8a",
    secondaryForeground: "#bfdbfe",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    accent: "#1e3a8a",
    accentForeground: "#bfdbfe",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    income: "#22c55e",
    expense: "#ef4444",
    border: "#334155",
    input: "#334155",
  },

  radius: 12,
};

export default colors;
